fbRepos = ['facebook/codemod', 'facebook/hhvm', 'facebook/xhp-lib', 'facebook/pyre2', 'facebook/flashcache',
           'facebook/open-graph-protocol', 'facebook/facebook-android-sdk', 'facebook/facebook-ios-sdk',
           'facebook/pfff', 'facebook/php-webdriver', 'facebook/swift', 'facebook/nifty', 'facebook/folly', 'facebook/jcommon',
           'facebook/node-haste', 'facebook/sparts', 'facebook/facebook-oss-pom', 'facebook/caf8teen', 'facebook/watchman',
           'facebook/rocksdb', 'facebook/FBMock', 'facebook/libphenom', 'facebook/chef-utils', 'facebook/mysql-5.6', 'facebook/giraph', 
           'facebook/buck', 'facebook/commoner', 'facebook/xctool', 'facebook/emitter', 'facebook/hblog', 'facebook/react', 
           'facebook/fbthrift', 'facebook/fishhook', 'facebook/glusterfs', 'facebook/react-devtools', 'facebook/pyaib',
           'facebook/ios-snapshot-test-case', 'facebook/regenerator', 'facebook/rebound', 'facebook/easymock',
           'facebook/clang-as-ios-dylib', 'facebook/jest', 'facebook/origami', 'facebook/puewue-backend', 'facebook/puewue-frontend', 
           'facebook/mcrouter', 'facebook/conceal', 'facebook/planout', 'facebook/bistro', 'facebook/shortcuts-for-framer',
           'facebook/liblogfaf', 'facebook/Shimmer', 'facebook/chisel', 'facebook/facebook-clang-plugins', 'facebook/KVOController',
           'facebook/Specs', 'facebook/Tweaks', 'facebook/IT-CPE', 'facebook/augmented-traffic-control', 'facebook/pop',
           'facebook/Haxl', 'facebook/css-layout', 'facebook/facebook-php-sdk-v4', 'facebook/proguard', 
           'facebook/pose-aligned-deep-networks', 'facebook/fb-adb', 'facebook/tac_plus', 'facebook/facebook-php-ads-sdk', 'facebook/thpp',
           'facebook/AsyncDisplayKit', 'facebook/immutable-js', 'facebook/fblualib', 'facebook/flux', 'facebook/wdt', 'facebook/rebound-js', 
           'facebook/dfuse', 'facebook/osquery', 'facebook/jsx', 'facebook/facebook-python-ads-sdk', 'facebook/grocery-delivery', 
           'facebook/taste-tester', 'facebook/between-meals', 'facebook/fbpca', 'facebook/fatal', 'facebook/proxygen', 'facebook/powermock',
           'facebook/ds2', 'facebook/flow', 'facebook/fbnn', 'facebook/fbcunn', 'facebook/wangle', 'facebook/fbcuda', 'facebook/fbtorch',
           'facebook/react-native', 'facebook/iTorch', 'facebook/stetho', 'facebook/infer', 'facebook/mysqlclient-python', 
           'facebook/fixed-data-table', 'facebook/libafdt', 'facebook/FBFetchedResultsController', 'facebook/ThreatExchange', 
           'facebook/squangle', 'facebook/shimmer-android', 'facebook/nuclide', 'facebook/fresco', 'facebook/device-year-class', 
           'facebook/jscodeshift', 'facebook/openbmc', 'facebook/fboss', 'facebook/network-connection-class', 'facebook/componentkit', 
           'facebook/Stack-RNN', 'facebook/SCRNNs', 'facebook/C3D', 'facebook/react-native-applinks', 'facebook/PathPicker', 
           'facebook/CParser', 'facebook/gnlpy', 'facebook/fbjs', 'facebook/eyescream', 'facebook/FLAnimatedImage', 'facebook/fbpush', 
           'facebook/graphql', 'facebook/android-jsc', 'facebook/react-native-fbsdk', 'facebook/ztorch', 'facebook/luaffifb', 
           'facebook/hack-codegen', 'facebook/Recipes-for-AutoPkg', 'facebook/relay', 'facebook/NAMAS', 
           'facebook/screenshot-tests-for-android', 'facebook/facebook-sdk-for-unity', 'facebook/WebDriverAgent', 
           'facebook/FBSimulatorControl', 'facebook/ocpjbod', 'facebook/dataloader', 'facebook/homebrew-fb', 'facebook/bAbI-tasks', 
           'facebook/MemNN', 'facebook/xcbuild', 'facebook/Conditional-character-based-RNN', 'facebook/robolectric', 'facebook/SoLoader', 
           'facebook/mention-bot', 'facebook/fb-caffe-exts', 'facebook/facebook-java-ads-sdk', 'facebook/learningSimpleAlgorithms', 
           'facebook/MazeBase', 'facebook/transform', 'facebook/fb.resnet.torch', 'facebook/UdpPinger', 'facebook/fbtracert', 
           'facebook/draft-js', 'facebook/fb-util-for-appx', 'facebook/UETorch', 'facebook/facebook-instant-articles-sdk-php']